package myNews.data.service.FakeAPI;

import java.util.List;

import myNews.data.repositories.model.Articles;

import static myNews.data.service.FakeAPI.FakeApiServiceGenerator.generateArticles;

/**
 * Created by Remy Pouzet on 25/11/2019.
 */

public class FakeFakeApiServiceInterface implements FakeApiServiceInterface
{

    private List<Articles> articles = generateArticles();

    /**
     * Return a list of {@link Articles}
     * Those articles must be generated by {@link FakeApiServiceGenerator}
     */

    public List<Articles> getArticles()
    {
        return articles;
    }
}