package myNews.data.service.API;

import java.util.List;

import myNews.data.repositories.model.Articles;

import static myNews.data.service.API.FakeApiServiceGenerator.generateArticles;

/**
 * Created by Remy Pouzet on 25/11/2019.
 */

public class FakeApiService implements ApiService
{

    private List<Articles> articles = generateArticles();

    /**
     * Return a list of {@link Articles}
     * Those users must be generated by {@link FakeApiServiceGenerator}
     */

    public List<Articles> getArticles()
    {
        // TODO: A modifier
        return null;
    }
}